<?xml version="1.0"?>
<configuration>
  <configSections>
    <section name="MySQL" type="MySql.Data.MySqlClient.MySqlConfiguration,MySql.Data"/>
  </configSections>
  <MySQL>
    <Replication>
      <ServerGroups>
        <Group name="Group1" groupType="MySql.Data.MySqlClient.Replication.ReplicationRoundRobinServerGroup">
          <Servers>
            <Server name="source" IsSource="true" connectionstring="server=localhost;port=3307;uid=root;password=;logging=true;"/>
            <Server name="replica1" IsSource="false" connectionstring="server=localhost;port=3308;uid=lbuser;password=lbpass;logging=true;"/>
          </Servers>
        </Group>
        <Group name="Group2">
          <Servers>
            <Server name="replica1" connectionstring="server=localhost;port=3307;uid=lbuser;password=lbpass;"/>
            <Server name="replica2" IsSource="false" connectionstring="server=localhost;port=3308;uid=lbuser;password=lbpass;"/>
            <!-- This unexisting connection is added intentionally to test failover -->
            <Server name="replicaX" IsSource="false" connectionstring="server=nonexisting;port=5000;uid=nonexisting;password=any;"/>
          </Servers>
        </Group>
      </ServerGroups>
    </Replication>
  </MySQL>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.1"/>
  </startup>
</configuration>
